name: Main

on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - "*"

env:
  GO_VERSION: 1.22.2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go test -v ./...

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - uses: ko-build/setup-ko@v0.6
      with:
        version: v0.15.2

    - run: |
        ko build \
          --platform=linux/arm64,linux/amd64 \
          --tags ${GITHUB_REF#refs/*/},latest \
          --bare \
          ./cmd/entry

    - uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
